from urllib.parse import urlsplit

from app.db.models import Agent, PeerRequest
from app.peer.validation import (
    asn_link_local_address,
    normalize_asn_number,
    normalize_wireguard_mtu,
    wireguard_listen_port,
)


def agent_wireguard_endpoint(peer: PeerRequest, agent: Agent) -> str:
    """Public WireGuard endpoint a peer dials: the agent host plus the derived listen port."""
    parsed = urlsplit(agent.url if "://" in agent.url else f"//{agent.url}")
    host = parsed.hostname or agent.url.strip()
    if ":" in host:  # bare IPv6, wrap for host:port form
        host = f"[{host}]"
    try:
        port = wireguard_listen_port(peer.asn)
    except ValueError:
        return f"{host}:<wg-port>"
    return f"{host}:{port}"


def peer_link_ip(peer: PeerRequest) -> str:
    return peer.peer_link_address.strip().split("/", 1)[0]


def local_link_ip(peer: PeerRequest) -> str:
    return peer.local_link_address.strip().split("/", 1)[0]


def post_up_address(peer: PeerRequest) -> str:
    return f"{local_link_ip(peer)}/64"


def local_default_link_ip(local_asn: str) -> str:
    if local_asn.strip() in {"", "<our-asn>"}:
        return "<our-link-local>"
    return asn_link_local_address(local_asn)


def peer_wireguard_mtu(peer: PeerRequest) -> int:
    return normalize_wireguard_mtu(getattr(peer, "wg_mtu", None))


def peer_protocol_name(peer: PeerRequest, agent: Agent) -> str:
    """WireGuard interface, ``.conf`` filenames, and BIRD protocol name for this peer.

    Format is ``DN42_<last4>`` where ``<last4>`` is the last four digits of the peer's ASN. dn42
    ASNs (``424242xxxx``) are uniquely identified by those four digits, and a PoP peers with any
    ASN at most once, so this never collides within a PoP. ``wg-quick`` names the interface after
    the config filename, so all three stay in sync from this one value (≤15-char interface limit,
    and it satisfies the agent's ``safeNameRE``).

    本對等的 WireGuard 介面、設定檔名與 BIRD protocol 名,格式為 ``DN42_<對方 ASN 後 4 位>``。
    """
    return f"DN42_{normalize_asn_number(peer.asn)[-4:]}"


def peering_info(peer: PeerRequest, agent: Agent) -> dict[str, str]:
    """The "our side" parameters a peer needs to bring their tunnel up after a successful deploy.

    ``endpoint`` is the WireGuard endpoint they dial (agent host + ASN-derived listen port),
    ``public_key`` is this PoP's WireGuard key, and ``tunnel_ip`` is our in-tunnel (link-local)
    address — which is also the BGP neighbor address their side should point at. The public key
    falls back to the visible placeholder (as in ``render_user_config``) when the PoP key has not
    been fetched yet, so the peer is never silently handed a blank key.

    對端在部署成功後建立隧道所需的「我方」參數:``endpoint`` 為對端撥號的 WireGuard 端點(agent 主機
    + 由 ASN 推導的監聽埠),``public_key`` 為本 PoP 的 WireGuard 公鑰,``tunnel_ip`` 為我方隧道內
    (link-local)位址,亦即對端 BGP 應指向的鄰居位址。公鑰未抓取時退回可見佔位字串。
    """
    return {
        "endpoint": agent_wireguard_endpoint(peer, agent),
        "public_key": agent.wg_public_key or "<our-wireguard-public-key>",
        "tunnel_ip": local_link_ip(peer),
        "mtu": str(peer_wireguard_mtu(peer)),
    }


def render_user_config(peer: PeerRequest, agent: Agent, local_asn: str = "<our-asn>") -> str:
    local_neighbor = local_default_link_ip(local_asn)
    # Use the PoP's cached public key; fall back to the visible placeholder if it has not been
    # fetched yet, so the peer never silently gets a wrong key (the admin can Refresh Pubkey).
    our_public_key = agent.wg_public_key or "<our-wireguard-public-key>"
    return f"""# Generated dn42 peer config for AS{peer.asn} on agent {agent.name}

[Interface]
# PrivateKey = <your-private-key>
# Address = {peer_link_ip(peer)}/64
MTU = {peer_wireguard_mtu(peer)}

[Peer]
PublicKey = {our_public_key}
Endpoint = {agent_wireguard_endpoint(peer, agent)}
AllowedIPs = 10.0.0.0/8, 172.20.0.0/14, 172.31.0.0/16, fd00::/8, fe80::/64
PersistentKeepalive = 25

# BGP
# Neighbor ASN: {local_asn}
# Neighbor IP: {local_neighbor}
# Your ASN: {peer.asn}
# Our side will expect your BGP neighbor address: {peer_link_ip(peer)}
"""


def render_wireguard_peer_config(
    peer: PeerRequest, agent: Agent, private_key_placeholder: str
) -> str:
    listen_port = wireguard_listen_port(peer.asn)
    return f"""# Generated by dn42 Autopeer for request #{peer.id}
# AS{peer.asn} on agent {agent.name}

[Interface]
PrivateKey = {private_key_placeholder}
ListenPort = {listen_port}
Table = off
MTU = {peer_wireguard_mtu(peer)}
PostUp = ip addr add {post_up_address(peer)} dev %i

[Peer]
Endpoint = {peer.endpoint}
PersistentKeepalive = 15
PublicKey = {peer.wg_public_key}
AllowedIPs = 10.0.0.0/8, 172.20.0.0/14, 172.31.0.0/16, fd00::/8, fe80::/64
"""


def render_bird_peer_config(peer: PeerRequest, agent: Agent, local_asn: str) -> str:
    local_asn_number = normalize_asn_number(local_asn)
    peer_asn_number = normalize_asn_number(peer.asn)
    protocol_name = peer_protocol_name(peer, agent)
    return f"""# Generated by dn42 Autopeer for request #{peer.id}
# BIRD2 peer snippet based on the dn42 wiki MP-BGP over IPv6 template.
# Requires a global template named `dnpeers` with local as {local_asn_number}.

protocol bgp {protocol_name} from dnpeers {{
  enable extended messages on;
  neighbor {peer_link_ip(peer)}%{protocol_name} as {peer_asn_number};
  source address {local_link_ip(peer)};
  direct;
  ipv4 {{
    extended next hop on;
  }};
}}
"""


def render_operator_config(peer: PeerRequest, agent: Agent, local_asn: str = "<our-asn>") -> str:
    return "\n".join(
        [
            render_wireguard_peer_config(peer, agent, "{{WIREGUARD_PRIVATE_KEY}}"),
            render_bird_peer_config(peer, agent, local_asn),
        ]
    )
