from urllib.parse import urlsplit

from app.db.models import Agent, PeerRequest
from app.peer.validation import asn_link_local_address, normalize_asn_number, wireguard_listen_port


def agent_wireguard_endpoint(peer: PeerRequest, agent: Agent) -> str:
    """Public WireGuard endpoint a peer dials: the agent host plus the derived listen port."""
    parsed = urlsplit(agent.url if "://" in agent.url else f"//{agent.url}")
    host = parsed.hostname or agent.url.strip()
    if ":" in host:  # bare IPv6, wrap for host:port form
        host = f"[{host}]"
    try:
        port = wireguard_listen_port(peer.asn)
    except ValueError:
        return f"{host}:<wg-port>"
    return f"{host}:{port}"


def peer_link_ip(peer: PeerRequest) -> str:
    return peer.peer_link_address.strip().split("/", 1)[0]


def local_link_ip(peer: PeerRequest) -> str:
    return peer.local_link_address.strip().split("/", 1)[0]


def post_up_address(peer: PeerRequest) -> str:
    return f"{local_link_ip(peer)}/64"


def local_default_link_ip(local_asn: str) -> str:
    if local_asn.strip() in {"", "<our-asn>"}:
        return "<our-link-local>"
    return asn_link_local_address(local_asn)


def peer_protocol_name(peer: PeerRequest, agent: Agent) -> str:
    return f"dn42p{peer.id}"


def render_user_config(peer: PeerRequest, agent: Agent, local_asn: str = "<our-asn>") -> str:
    local_neighbor = local_default_link_ip(local_asn)
    return f"""# Generated dn42 peer config for AS{peer.asn} on agent {agent.name}

[Interface]
# PrivateKey = <your-private-key>
# Address = {peer_link_ip(peer)}/64

[Peer]
PublicKey = <our-wireguard-public-key>
Endpoint = {agent_wireguard_endpoint(peer, agent)}
AllowedIPs = 172.16.0.0/12, fd00::/8
PersistentKeepalive = 25

# BGP
# Neighbor ASN: {local_asn}
# Neighbor IP: {local_neighbor}
# Your ASN: {peer.asn}
# Our side will expect your BGP neighbor address: {peer_link_ip(peer)}
"""


def render_wireguard_peer_config(peer: PeerRequest, agent: Agent, private_key_placeholder: str) -> str:
    listen_port = wireguard_listen_port(peer.asn)
    return f"""# Generated by dn42 Autopeer for request #{peer.id}
# AS{peer.asn} on agent {agent.name}

[Interface]
PrivateKey = {private_key_placeholder}
ListenPort = {listen_port}
Table = off
PostUp = ip addr add {post_up_address(peer)} dev %i

[Peer]
Endpoint = {peer.endpoint}
PersistentKeepalive = 15
PublicKey = {peer.wg_public_key}
AllowedIPs = 172.20.0.0/14,fd00::/8
"""


def render_bird_peer_config(peer: PeerRequest, agent: Agent, local_asn: str) -> str:
    local_asn_number = normalize_asn_number(local_asn)
    peer_asn_number = normalize_asn_number(peer.asn)
    protocol_name = peer_protocol_name(peer, agent)
    return f"""# Generated by dn42 Autopeer for request #{peer.id}
# BIRD2 peer snippet based on the dn42 wiki MP-BGP over IPv6 template.
# Requires a global template named `dnpeers` with local as {local_asn_number}.

protocol bgp {protocol_name} from dnpeers {{
  enable extended messages on;
  neighbor {peer_link_ip(peer)}%{protocol_name} as {peer_asn_number};
  source address {local_link_ip(peer)};
  direct;
  ipv4 {{
    extended next hop on;
  }};
}}
"""


def render_operator_config(peer: PeerRequest, agent: Agent, local_asn: str = "<our-asn>") -> str:
    return "\n".join(
        [
            render_wireguard_peer_config(peer, agent, "{{WIREGUARD_PRIVATE_KEY}}"),
            render_bird_peer_config(peer, agent, local_asn),
        ]
    )
