from app.db.models import Node, PeerRequest
from app.peer.validation import (
    extract_node_host,
    is_link_local,
    normalize_asn_number,
    normalize_wireguard_mtu,
    wireguard_listen_port,
)


def node_effective_asn(node: Node, fallback_asn: str) -> str:
    """Return the node ASN, falling back to LOCAL_ASN when the node leaves it blank."""
    asn = (node.asn or "").strip()
    return asn or (fallback_asn or "").strip()


def node_wireguard_endpoint(peer: PeerRequest, node: Node) -> str:
    """Public WireGuard endpoint a peer dials: node host plus ASN-derived listen port."""
    host = extract_node_host(node.url)
    if ":" in host:
        host = f"[{host}]"
    try:
        port = wireguard_listen_port(peer.asn)
    except ValueError:
        return f"{host}:<wg-port>"
    return f"{host}:{port}"


def peer_link_ip(peer: PeerRequest) -> str:
    return peer.peer_link_address.strip().split("/", 1)[0]


def local_link_ip(peer: PeerRequest) -> str:
    return peer.local_link_address.strip().split("/", 1)[0]


def post_up_address(peer: PeerRequest) -> str:
    return f"{local_link_ip(peer)}/64"


def peer_wireguard_mtu(peer: PeerRequest) -> int:
    return normalize_wireguard_mtu(getattr(peer, "wg_mtu", None))


def peer_protocol_name(peer: PeerRequest, node: Node) -> str:
    """WireGuard interface, config filename, and BIRD protocol name for this peer.

    Must be unique among all peers on one node: it is the wg-quick interface name, the
    ``<dir>/<name>.conf`` filename, and the BIRD protocol name, so a clash makes two
    peers clobber each other's tunnel and config. The ASN's last 4 digits collide when
    two ASNs share that suffix on the same node (e.g. AS4242425001 vs AS65001 -> 5001),
    so the peer UUID's last 4 hex chars disambiguate. Stays within the 15-char Linux
    interface-name limit (IFNAMSIZ): ``DN42_`` + 4 + ``_`` + 4 = 14 chars.
    """
    asn_suffix = normalize_asn_number(peer.asn)[-4:]
    return f"DN42_{asn_suffix}_{peer.id[-4:]}"


def peering_info(peer: PeerRequest, node: Node, local_asn: str = "<our-asn>") -> dict[str, str]:
    """Operator-side parameters a peer needs to configure their end."""
    display_asn = local_asn
    if local_asn != "<our-asn>":
        display_asn = normalize_asn_number(local_asn)
    return {
        "asn": display_asn,
        "ipv4": node.dn42_ipv4 or "",
        "ipv6": node.dn42_ipv6 or "",
        "link_local": local_link_ip(peer),
        "endpoint": node_wireguard_endpoint(peer, node),
        "public_key": node.wg_public_key or "<our-wireguard-public-key>",
        "tunnel_ip": local_link_ip(peer),
        "mtu": str(peer_wireguard_mtu(peer)),
    }


def render_user_config(peer: PeerRequest, node: Node, local_asn: str = "<our-asn>") -> str:
    if local_asn.strip() in {"", "<our-asn>"}:
        local_asn_display = "<our-asn>"
    else:
        local_asn_display = f"AS{normalize_asn_number(local_asn)}"
    local_neighbor = local_link_ip(peer) or "<our-link-local>"
    peer_ipv4 = peer.peer_dn42_ipv4 or "<your-dn42-ipv4>"
    peer_ipv6 = peer.peer_dn42_ipv6 or "<your-dn42-ipv6>"
    our_public_key = node.wg_public_key or "<our-wireguard-public-key>"
    bgp_extension_text = "enabled" if getattr(peer, "bgp_extended", True) else "disabled"
    return f"""# Generated dn42 peer config for AS{peer.asn} on node {node.name}

[Interface]
# PrivateKey = <your-private-key>
# Address = {peer_link_ip(peer)}/64
MTU = {peer_wireguard_mtu(peer)}

[Peer]
PublicKey = {our_public_key}
Endpoint = {node_wireguard_endpoint(peer, node)}
AllowedIPs = 10.0.0.0/8, 172.20.0.0/14, 172.31.0.0/16, fd00::/8, fe80::/64
PersistentKeepalive = 25

# BGP
# Neighbor ASN: {local_asn_display}
# Neighbor IP: {local_neighbor}
# Your ASN: {peer.asn}
# Our side will expect your BGP neighbor address: {peer_link_ip(peer)}
# Your DN42 IPv4: {peer_ipv4}
# Your DN42 IPv6: {peer_ipv6}
# BGP extensions: {bgp_extension_text}
"""


def render_wireguard_peer_config(
    peer: PeerRequest, node: Node, private_key_placeholder: str
) -> str:
    listen_port = wireguard_listen_port(peer.asn)
    endpoint_line = f"Endpoint = {peer.endpoint}\n" if peer.endpoint.strip() else ""
    return f"""# Generated by dn42 Autopeer for request {peer.id}
# AS{peer.asn} on node {node.name}

[Interface]
PrivateKey = {private_key_placeholder}
ListenPort = {listen_port}
Table = off
MTU = {peer_wireguard_mtu(peer)}
PostUp = ip addr add {post_up_address(peer)} dev %i

[Peer]
{endpoint_line}PersistentKeepalive = 15
PublicKey = {peer.wg_public_key}
AllowedIPs = 10.0.0.0/8, 172.20.0.0/14, 172.31.0.0/16, fd00::/8, fe80::/64
"""


def render_bird_peer_config(peer: PeerRequest, node: Node, local_asn: str) -> str:
    local_asn_number = normalize_asn_number(local_asn)
    peer_asn_number = normalize_asn_number(peer.asn)
    protocol_name = peer_protocol_name(peer, node)
    scope = f"%{protocol_name}" if is_link_local(peer.peer_link_address) else ""
    extended_enabled = getattr(peer, "bgp_extended", True)

    lines = [
        f"# Generated by dn42 Autopeer for request {peer.id}",
        "# BIRD2 peer snippet based on the dn42 wiki MP-BGP over IPv6 template.",
        f"# Requires a global template named `dnpeers` with local as {local_asn_number}.",
        "",
        f"protocol bgp {protocol_name} from dnpeers {{",
    ]
    if extended_enabled:
        lines.append("  enable extended messages on;")
    lines.extend(
        [
            f"  neighbor {peer_link_ip(peer)}{scope} as {peer_asn_number};",
            f"  source address {local_link_ip(peer)};",
            "  direct;",
        ]
    )
    if extended_enabled:
        lines.extend(["  ipv4 {", "    extended next hop on;", "  };"])
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_operator_config(peer: PeerRequest, node: Node, local_asn: str = "<our-asn>") -> str:
    return "\n".join(
        [
            render_wireguard_peer_config(peer, node, "{{WIREGUARD_PRIVATE_KEY}}"),
            render_bird_peer_config(peer, node, local_asn),
        ]
    )
